GET http://localhost:3000/gls/test


###
POST http://localhost:3000/jvs/
Content-Type: application/json

{ 
    "account_code": 111010001
}
###

GET http://localhost:3000/crs/1


###
POST http://localhost:3000/crs/
Content-Type: application/json

{ 
    "account_code": 111010001
}

###
PATCH http://localhost:3000/level3/620bc300e12e9b0c2866b576
Content-Type: application/json

{"level2_code": 21 }